name: Removing Excess Files
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    steps:
      - name: Remove File
        run: rm -rf /home/runner/work/AutomationTesting/AutomationTesting/github-pages-deploy-action-temp-deployment-folder