name: Schemas Script
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install schema2md
        run: npm install -g @adobe/jsonschema2md

      - name: Json schema to markdown
        run: jsonschema2md -d schema -o docs/SchemaMarkdown -e json

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown

      - name: Running header script
        run: scripts/header.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown

      - name: Generating directories
        run: scripts/demo.sh

      - name: Configuring paths
        run: scripts/editContent.sh
