name: Schema Script
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install schema2md
        run: sudo npm install -g @adobe/jsonschema2md

      - name: Json schema to markdown
        run: jsonschema2md -d schema -o docs/SchemaMarkdown -e json

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown

      - name: Running header script
        run: ./header.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown

      - name: Generating directories
        run: ./demo.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown

      - name: Configuring paths
        run: ./editContent.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: docs/SchemaMarkdown