name: Schemas Script
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jsonschema2md
        run: sudo npm install -g @adobe/jsonschema2md

      - name: Json schema to markdown
        run: jsonschema2md -d schema -o docs/docs/SchemaMarkdown -e json

      - name: Running header script
        run: sh ./scripts/header.sh

      - name: Generating directories
        run: sh ./scripts/generateDirectories.sh

      - name: Configuring paths
        run: sh ./scripts/editContent.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
